name: image_comparison
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  exif: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.2.0 
  get_it: ^7.6.7 
  image_picker: ^1.0.7
  intl: ^0.19.0
  mockito: ^5.4.4

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.3.4
  flutter_test:
    sdk: flutter
  solid_lints: ^0.1.4

flutter:
  uses-material-design: true
